# Generated by Django 2.2.5 on 2019-09-28 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated at', null=True)),
                ('title', models.CharField(max_length=340, verbose_name='title')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in minutes', verbose_name='duration')),
                ('year', models.PositiveIntegerField(null=True, verbose_name='year')),
                ('created_by', models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.CASCADE, related_name='movie_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updated by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
