# Generated by Django 2.2.5 on 2019-09-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated at', null=True)),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('created_by', models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.CASCADE, related_name='genre_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updated by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated at', null=True)),
                ('name', models.CharField(max_length=340, verbose_name='name')),
                ('created_by', models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.CASCADE, related_name='director_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updated by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Director', verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Genre', verbose_name='Genre'),
        ),
    ]
