# Generated by Django 2.2.5 on 2019-09-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190928_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='starts',
            field=models.PositiveIntegerField(default=0, verbose_name='stars'),
        ),
    ]
