# Generated by Django 2.2.5 on 2019-09-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_movie_starts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='starts',
            new_name='stars',
        ),
    ]
