# Generated by Django 2.2.5 on 2019-10-17 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20190929_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='Updated at', null=True)),
                ('rate', models.PositiveIntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'regular'), (4, 'good'), (5, 'very good')], verbose_name='rate')),
                ('created_by', models.ForeignKey(help_text='Created by', on_delete=django.db.models.deletion.CASCADE, related_name='rating_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updated by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
