# Generated by Django 2.2.5 on 2019-10-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.FloatField(default=0, verbose_name='stars'),
        ),
    ]
